# 5.1 Introduction to pandas Data Structures

In [1]:
import pandas as pd

In [2]:
from pandas import Series, DataFrame

## 5.1.1 Series

A Series is a one-dimensional array-like object containing a sequence of values (of similar types to NumPy types) and an associated array of data labels, called its index.

In [3]:
obj = pd.Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [4]:
obj.values

array([ 4,  7, -5,  3])

In [4]:
obj.index # like range(4)

RangeIndex(start=0, stop=4, step=1)

In [5]:
list(obj.index)

[0, 1, 2, 3]

In [6]:
obj2 = pd.Series([4, 7, -5, 3], index = ['d','b','a','c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [7]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [8]:
obj2['a']

-5

In [9]:
obj2['d']

4

In [10]:
obj2[['c','a','d']]

c    3
a   -5
d    4
dtype: int64

In [13]:
obj2[[3,2,0]]

c    3
a   -5
d    4
dtype: int64

In [14]:
obj > 2

0     True
1     True
2    False
3     True
dtype: bool

In [15]:
obj2[obj2 > 0]

d    4
b    7
c    3
dtype: int64

In [16]:
obj2 * 2

d     8
b    14
a   -10
c     6
dtype: int64

In [17]:
import numpy as np
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

Another way to think about a Series is as a fixed-length, ordered dict, as it is a mapping of index values to data values

In [18]:
'b' in obj2

True

In [19]:
'e' in obj2

False

In [22]:
4 in obj2

False

Create a Series from passing a dict

In [23]:
sdata = {'Ohio':35000, 'Texas':71000, 'Oregon':16000, 'Utah':5000}
sdata

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [27]:
type(sdata)

dict

In [24]:
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [28]:
type(obj3)

pandas.core.series.Series

In [29]:
states = ['California','Ohio','Oregon','Texas']
obj4 = pd.Series(sdata, index = states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [30]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [31]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [32]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [34]:
obj4.notnull()

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [35]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [36]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

Similar to a join operation in database

In [37]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [38]:
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [39]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [40]:
obj.index = ['Bob','Steve','Jeff','Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [41]:
obj.dtype

dtype('int64')

## 5.1.2 DataFrame

A DataFrame represents a rectangular table of data and contains an ordered collection of columns, each of which can be a different value type (numeric, string, boolean, etc.). The DataFrame has both a row and column index; it can be thought of as a dict of Series all sharing the same index. Under the hood, the data is stored as one or more two-dimensional blocks rather than a list, dict, or some other collection of one-dimensional arrays.

In [42]:
data = {'state':['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada'],
        'year':[2000,2001,2002,2001,2002,2003],
        'pop':[1.5,1.7,3.6,2.4,2.9,3.2]}
frame = pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [44]:
type(frame)

pandas.core.frame.DataFrame

In [45]:
frame.index

RangeIndex(start=0, stop=6, step=1)

In [47]:
frame.values

array([['Ohio', 2000, 1.5],
       ['Ohio', 2001, 1.7],
       ['Ohio', 2002, 3.6],
       ['Nevada', 2001, 2.4],
       ['Nevada', 2002, 2.9],
       ['Nevada', 2003, 3.2]], dtype=object)

In [48]:
frame.values.shape

(6, 3)

In [49]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [50]:
pd.DataFrame(data, columns = ['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [52]:
frame2 = pd.DataFrame(data, 
                      columns = ['year','state','pop','debt'], 
                      index = ['one','two','three','four','five','six'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [53]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [54]:
frame2.index

Index(['one', 'two', 'three', 'four', 'five', 'six'], dtype='object')

In [55]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, nan],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, nan],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [56]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [69]:
frame2.state

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [68]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [77]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [78]:
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [79]:
frame2['debt'] = np.arange(6.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [80]:
val = pd.Series([-1.2, -1.5, -1.7], index = ['two','four','five'])
val

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [81]:
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [82]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [83]:
del frame2['eastern']
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [84]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

Nested dict of dicts. If the nested dict is passed to the DataFrame, pandas will interpret the outer dict keys as the columns and the inner keys as the row indices

In [85]:
pop = {'Nevada':{2001:2.4,2002:2.9},
       'Ohio':{2000:1.5, 2001:1.7, 2002:3.6}}
frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

Transpose the DataFrame, swap rows and columns 

In [86]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [88]:
frame3.T.index

Index(['Nevada', 'Ohio'], dtype='object')

In [89]:
frame3.T.columns 

Int64Index([2001, 2002, 2000], dtype='int64')

In [90]:
pd.DataFrame(pop, index = [2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [91]:
pdata = {'Ohio':frame3['Ohio'][:-1],
         'Nevada':frame3['Nevada'][:2]}
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [92]:
frame3.index.name = 'year'
frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [94]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [95]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

## 5.1.3 Index Objects

In [96]:
obj = pd.Series(range(3),index = ['a','b','c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [99]:
list(index)

['a', 'b', 'c']

In [97]:
index[1:]

Index(['b', 'c'], dtype='object')

Index objects are immutable. Immutability makes it safer to share Index objects among data structures

In [98]:
index[1] = 'd'

TypeError: Index does not support mutable operations

In [100]:
labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [101]:
obj2 = pd.Series([1.5,-2.5,0], index = labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [102]:
obj2.index

Int64Index([0, 1, 2], dtype='int64')

In [103]:
obj2.index is labels 

True

In addition to being array-like, an Index also behaves like a fixed-size set

In [104]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [105]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [106]:
frame3.index

Int64Index([2001, 2002, 2000], dtype='int64', name='year')

In [107]:
'Ohio' in frame3.columns

True

In [108]:
2003 in frame3.index

False

In [109]:
2002 in frame3.index

True

Unlike Python sets, a pandas Index can contain duplicate labels. Selections with duplicate labels will select all occurrences of that label

In [110]:
dup_labels = pd.Index(['foo','foo','bar','bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

# 5.2 Essential Functionality

## 5.2.1 Reindexing

In [111]:
import pandas as pd
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index = ['d','b','a','c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [112]:
obj2 = obj.reindex(['a','b','c','d','e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [113]:
obj3 = pd.Series(['blue','purple','yellow'], index = [0,2,4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [114]:
obj3.reindex(range(6), method = 'ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [116]:
obj3.reindex(range(6), method = 'bfill')

0      blue
1    purple
2    purple
3    yellow
4    yellow
5       NaN
dtype: object

In [117]:
import numpy as np
frame = pd.DataFrame(np.arange(9).reshape((3,3)),
                    index = ['a','c','d'],
                    columns = ['Ohio','Texas','California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [118]:
frame2 = frame.reindex(['a','b','c','d'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [119]:
states = ['Texas','Utah','California']
frame.reindex(columns = states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [121]:
frame.loc[['a','b','c','d'],states] #Passing list-likes to .loc or [] with any missing labels is no longer supported

KeyError: 'Passing list-likes to .loc or [] with any missing labels is no longer supported, see https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike'

In [125]:
frame.loc[['a','c'], ['Ohio','Texas']]

Ohio  Texas
a     0      1
c     3      4

## 5.2.2 Dropping Entries from an Axis

In [126]:
obj = pd.Series(np.arange(5.), index = ['a','b','c','d','e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [127]:
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [128]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [133]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                   index = ['Ohio', 'Colorado','Utah','New York'],
                   columns = ['one','two','three','four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [134]:
data.drop(['Colorado','Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [135]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [136]:
data.drop('two',axis = 1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [137]:
data.drop(['two', 'four'], axis = 'columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

Many functions, like drop, which modify the size or shape of a Series or DataFrame, can manipulate an object in-place without returning a new object

In [138]:
obj.drop('c', inplace = True)
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

## 5.2.3 Indexing, Selection, and Filtering

In [139]:
obj = pd.Series(np.arange(4.), index = ['a','b','c','d'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [140]:
obj['b']

1.0

In [141]:
obj[1]

1.0

In [142]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [143]:
obj[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [144]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [145]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [146]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [147]:
obj['b':'c'] = 5
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [148]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                   index = ['Ohio','Colorado','Utah','New York'],
                   columns = ['one','two','three','four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [149]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [150]:
data[['three','one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

The row selection syntax data[:2] is provided as a convenience. Passing a single element or a list to the [] operator selects columns

In [44]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [151]:
data[:1]

one  two  three  four
Ohio    0    1      2     3

In [159]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [160]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [161]:
data[data < 5] = 0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [162]:
data.loc['Colorado',['two','three']]

two      5
three    6
Name: Colorado, dtype: int64

In [164]:
data.iloc[2,[3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [165]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [166]:
data.iloc[[1,2],[3,0,1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [167]:
data.loc[:'Utah','two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [169]:
data.iloc[:,:3]

one  two  three
Ohio        0    0      0
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [168]:
data.iloc[:,:3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

## 5.2.4 Integer Indexes

In [170]:
ser = pd.Series(np.arange(3.))
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [171]:
ser[-1]

KeyError: -1

In [172]:
ser.loc[1]

1.0

In [173]:
ser.iloc[1]

1.0

In [174]:
ser2 = pd.Series(np.arange(3.), index = ['a','b','c'])
ser2

a    0.0
b    1.0
c    2.0
dtype: float64

In [175]:
ser2[-1]

2.0

In [176]:
ser[1]

1.0

In [177]:
ser[:1]

0    0.0
dtype: float64

In [178]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [179]:
ser.iloc[:1]

0    0.0
dtype: float64

## 5.2.5 Arithmetic and Data Alignment

When adding together objects, if any index pairs are not the same, the respective index in the result will be the union of the index pairs. For users with database experience, this is similar to an automatic outer join on the index labels.

In [180]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index = ['a','c','d','e'])
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [181]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index = ['a','c','e','f','g'])
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [182]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In the case of DataFrame, alignment is performed on both the rows and the columns

In [183]:
import numpy as np
df1 = pd.DataFrame(np.arange(9.).reshape((3,3)),columns = list('bcd'),index = ['Ohio','Texas','Colorado'])
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [184]:
df2 = pd.DataFrame(np.arange(12.).reshape((4,3)),columns = list('bde'),index = ['Utah','Ohio','Texas','Oregon'])
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [185]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [186]:
df1 = pd.DataFrame({'A':[1,2]})
df2 = pd.DataFrame({'B':[3,4]})

In [187]:
df1

A
0  1
1  2

In [188]:
df2

B
0  3
1  4

In [189]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

In [190]:
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)),
                  columns = list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)),
                  columns = list('abcde'))

In [191]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [192]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [193]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [194]:
df2.loc[1,'b']

6.0

In [195]:
df2.loc[1,'b'] = np.nan

In [196]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [197]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [198]:
df1.add(df2,fill_value = 0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [199]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [200]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [201]:
df1.reindex(columns = df2.columns, fill_value = 0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [202]:
arr = np.arange(12.).reshape((3,4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [203]:
arr[0]

array([0., 1., 2., 3.])

In [204]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

When we subtract arr[0] from arr, the subtraction is performed once for each row. This is referred to as broadcasting

In [205]:
frame = pd.DataFrame(np.arange(12.).reshape((4,3)),
                    columns = list('bde'),
                    index = ['Utah','Ohio','Texas','Oregon'])
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [206]:
series = frame.iloc[0]
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

By default, arithmetic between DataFrame and Series matches the index of the Series on the DataFrame’s columns, broadcasting down the rows

In [207]:
frame - series 

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [208]:
series2 = pd.Series(range(3),index = ['b','e','f'])
series2

b    0
e    1
f    2
dtype: int64

In [209]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [210]:
series3 = frame['d']
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [211]:
frame + series3

Ohio  Oregon  Texas  Utah   b   d   e
Utah     NaN     NaN    NaN   NaN NaN NaN NaN
Ohio     NaN     NaN    NaN   NaN NaN NaN NaN
Texas    NaN     NaN    NaN   NaN NaN NaN NaN
Oregon   NaN     NaN    NaN   NaN NaN NaN NaN

In [212]:
frame.sub(series3, axis = 'index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

## 5.2.6 Function Application and Mapping

In [213]:
frame = pd.DataFrame(np.random.randn(4,3),
                    columns = list('bde'),
                    index = ['Utah','Ohio','Texas','Oregon'])
frame

b         d         e
Utah    1.248233 -1.239433 -1.215271
Ohio    0.573874 -0.032859  0.210636
Texas  -0.099192  0.661381 -0.013044
Oregon -0.836471 -0.617666  0.200122

In [214]:
np.abs(frame)

b         d         e
Utah    1.248233  1.239433  1.215271
Ohio    0.573874  0.032859  0.210636
Texas   0.099192  0.661381  0.013044
Oregon  0.836471  0.617666  0.200122

Apply a function on one-dimensional arrays to each column or row. DataFrame's apply method does this

In [215]:
f = lambda x: x.max() - x.min()

In [216]:
frame.apply(f)

b    2.084704
d    1.900815
e    1.425907
dtype: float64

In [218]:
frame.apply(f, axis = 'index')

b    2.084704
d    1.900815
e    1.425907
dtype: float64

In [219]:
frame.apply(f, axis = 'columns')

Utah      2.487667
Ohio      0.606733
Texas     0.760574
Oregon    1.036593
dtype: float64

In [220]:
frame.apply(f, axis = 0)

b    2.084704
d    1.900815
e    1.425907
dtype: float64

In [221]:
frame.apply(f, axis = 1)

Utah      2.487667
Ohio      0.606733
Texas     0.760574
Oregon    1.036593
dtype: float64

In [222]:
def f(x):
    return pd.Series([x.min(),x.max()],index = ['min','max'])

frame.apply(f)

b         d         e
min -0.836471 -1.239433 -1.215271
max  1.248233  0.661381  0.210636

In [223]:
format = lambda x: '%.2f' % x

In [224]:
frame.applymap(format)

b      d      e
Utah     1.25  -1.24  -1.22
Ohio     0.57  -0.03   0.21
Texas   -0.10   0.66  -0.01
Oregon  -0.84  -0.62   0.20

In [225]:
frame['e'].map(format)

Utah      -1.22
Ohio       0.21
Texas     -0.01
Oregon     0.20
Name: e, dtype: object

## 5.2.7 Sorting and Ranking

In [226]:
obj = pd.Series(range(4),index = ['d','a','b','c'])
obj

d    0
a    1
b    2
c    3
dtype: int64

In [227]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [228]:
frame = pd.DataFrame(np.arange(8).reshape((2,4)),
                    index = ['three','one'],
                    columns = ['d','a','b','c'])
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [229]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [230]:
frame.sort_index(axis = 'index')

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [231]:
frame.sort_index(axis = 0)

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [232]:
frame.sort_index(axis = 'columns')

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [233]:
frame.sort_index(axis = 1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [234]:
frame.sort_index(axis = 1, ascending = False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [235]:
obj = pd.Series([4,7,-3,2])
obj

0    4
1    7
2   -3
3    2
dtype: int64

In [236]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [237]:
obj = pd.Series([4,np.nan,7,np.nan,-3,2])
obj

0    4.0
1    NaN
2    7.0
3    NaN
4   -3.0
5    2.0
dtype: float64

In [238]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [239]:
frame = pd.DataFrame({'b':[4,7,-3,2],'a':[0,1,0,1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [240]:
frame.sort_values(by = 'b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [241]:
frame.sort_values(by = ['a','b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [242]:
obj = pd.Series([7,-5,7,4,2,0,4])
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [243]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [244]:
obj.rank(method = 'first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [245]:
obj.rank(ascending = False, method = 'max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [246]:
frame = pd.DataFrame({'b':[4.3, 7, -3, 2], 'a':[0,1,0,1], 'c':[-2, 5, 8, -2.5]})
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [247]:
frame.sort_index(axis = 1)

a    b    c
0  0  4.3 -2.0
1  1  7.0  5.0
2  0 -3.0  8.0
3  1  2.0 -2.5

In [248]:
frame.rank(axis = 'columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [249]:
frame.rank(axis = 'index')

b    a    c
0  3.0  1.5  2.0
1  4.0  3.5  3.0
2  1.0  1.5  4.0
3  2.0  3.5  1.0

## 5.2.8 Axis Indexes with Duplicate Lables

In [250]:
obj = pd.Series(range(5),index = ['a','a','b','b','c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [251]:
obj.index.is_unique

False

In [252]:
obj['a']

a    0
a    1
dtype: int64

In [253]:
obj.loc['a']

a    0
a    1
dtype: int64

In [254]:
obj['c']

4

In [255]:
df = pd.DataFrame(np.random.randn(4,3), index = ['a','a','b','b'])
df

0         1         2
a  1.472233 -0.707638  0.453938
a  0.498693  0.313043 -1.342864
b  1.333666  0.293011 -1.475486
b  0.644965 -1.178362  1.202497

In [256]:
df.loc['b']

0         1         2
b  1.333666  0.293011 -1.475486
b  0.644965 -1.178362  1.202497

In [257]:
df.loc['a']

0         1         2
a  1.472233 -0.707638  0.453938
a  0.498693  0.313043 -1.342864

# 5.3 Summarizing and Computing Descriptive Statistics

In [258]:
df = pd.DataFrame([[1.4, np.nan],[7.1, -4.5],
                  [np.nan, np.nan],[0.75, -1.3]],
                 index = ['a','b','c','d'],
                 columns = ['one', 'two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [259]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [261]:
df.sum(axis = 'index')

one    9.25
two   -5.80
dtype: float64

In [262]:
df.sum(axis = 0)

one    9.25
two   -5.80
dtype: float64

In [263]:
df.sum(axis = 'columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [264]:
df.sum(axis = 1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [265]:
df.mean(axis = 'columns', skipna = False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [266]:
df.mean(axis = 'columns', skipna = True)

a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

In [267]:
df.idxmax()

one    b
two    d
dtype: object

In [281]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [282]:
df.cumsum(axis = 0)

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [283]:
df.cumsum(axis = 1)

one   two
a  1.40   NaN
b  7.10  2.60
c   NaN   NaN
d  0.75 -0.55

In [278]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [279]:
obj = pd.Series(['a','a','b','c'] * 4)
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [284]:
df.count()

one    3
two    2
dtype: int64

## 5.3.1 Correlation and Covariance

In [285]:
conda install pandas-datareader

Solving environment: done

## Package Plan ##

  environment location: /Users/boyuan/anaconda3/envs/Python

  added / updated specs:
    - pandas-datareader


The following NEW packages will be INSTALLED:

  icu                pkgs/main/osx-64::icu-58.2-h0a44026_3
  libiconv           pkgs/main/osx-64::libiconv-1.16-h1de35cc_0
  libxml2            pkgs/main/osx-64::libxml2-2.9.9-hf6e021a_1
  libxslt            pkgs/main/osx-64::libxslt-1.1.33-h33a18ac_0
  lxml               pkgs/main/osx-64::lxml-4.5.0-py37hef8c89e_0
  pandas-datareader  pkgs/main/noarch::pandas-datareader-0.8.1-py_0


Preparing transaction: done
Verifying transaction: done
Executing transaction: done

Note: you may need to restart the kernel to use updated packages.


In [3]:
import pandas_datareader.data as web
all_data = {ticker: web.get_data_yahoo(ticker)
           for ticker in ['AAPL','IBM','MSFT','GOOG']}
price = pd.DataFrame({ticker: data['Adj Close']
                    for ticker, data in all_data.items()})
volume = pd.DataFrame({ticker: data['Volume']
                    for ticker, data in all_data.items()})

In [4]:
returns = price.pct_change()
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2020-05-11  0.015735 -0.003252  0.011154  0.010725
2020-05-12 -0.011428 -0.019006 -0.022652 -0.019611
2020-05-13 -0.012074 -0.037668 -0.015122 -0.019197
2020-05-14  0.006143  0.010542  0.004339  0.005040
2020-05-15 -0.005912  0.000257  0.014568  0.012580

In [5]:
returns['MSFT'].corr(returns['IBM'])

0.6003537677880831

In [6]:
returns['MSFT'].cov(returns['IBM'])

0.0001621618542275402

In [7]:
returns['MSFT'].corr(returns['MSFT'])

1.0

In [8]:
returns.MSFT.corr(returns.IBM)

0.6003537677880831

In [9]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.532662  0.710548  0.642264
IBM   0.532662  1.000000  0.600354  0.530280
MSFT  0.710548  0.600354  1.000000  0.751001
GOOG  0.642264  0.530280  0.751001  1.000000

In [10]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000328  0.000151  0.000221  0.000199
IBM   0.000151  0.000246  0.000162  0.000142
MSFT  0.000221  0.000162  0.000296  0.000221
GOOG  0.000199  0.000142  0.000221  0.000293

In [14]:
returns.corrwith(returns.IBM)

AAPL    0.532662
IBM     1.000000
MSFT    0.600354
GOOG    0.530280
dtype: float64

In [13]:
volume.tail()

AAPL        IBM        MSFT     GOOG
Date                                                  
2020-05-11  36486600.0  3535300.0  30892700.0  1412100
2020-05-12  40575300.0  4784500.0  32038200.0  1390600
2020-05-13  50155600.0  5882800.0  44711500.0  1812600
2020-05-14  39732300.0  5259400.0  41873900.0  1603100
2020-05-15  41561200.0  4785800.0  46597900.0  1705700

In [15]:
returns.corrwith(volume)

AAPL   -0.141855
IBM    -0.105762
MSFT   -0.066293
GOOG   -0.039168
dtype: float64

## 5.3.2 Unique Values, Value Counts, and Membership

In [16]:
obj = pd.Series(['c','a','d','a','a','b','b','c','c'])
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [17]:
uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [18]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [19]:
pd.value_counts(obj.values, sort = False)

d    1
a    3
c    3
b    2
dtype: int64

In [21]:
obj.value_counts(sort = False)

d    1
a    3
c    3
b    2
dtype: int64

In [22]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [23]:
mask = obj.isin(['b','c'])
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [24]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [27]:
obj[obj.isin(['b','c'])]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [28]:
to_match = pd.Series(['c','a','b','b','c','a'])
unique_vals = pd.Series(['c','b','a'])
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2])

Compute a histogram on multiple related columns in a DataFrame.

In [30]:
data = pd.DataFrame({'Ou1':[1,3,4,3,4],
                     'Ou2':[2,3,1,2,3],
                     'Ou3':[1,5,2,4,4]})
data

Ou1  Ou2  Ou3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [31]:
result = data.apply(pd.value_counts).fillna(0)
result

Ou1  Ou2  Ou3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

# 5.4 Conclusion